version = 1

exclude_patterns = [
  "dist/**",
  "node_modules/**",
  "demo/**",
  "coverage/**",
  "public/**",
]

test_patterns = [
  "tests/**",
  "benchmarks/**",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser", "nodejs"]
  dependency_file_paths = ["package.json"]

[[code_formatters]]
name = "prettier"
enabled = true
